package com.restartthread.shared.ui

import com.restartthread.shared.presentation.SwitchCurrentChoice

data class RestartThreadUiActions(
    val leaveFirstThread: () -> Unit,
    val tryExample: () -> Unit,
    val showAccountOffer: () -> Unit,
    val completeAccountStep: () -> Unit,
    val signIn: () -> Unit,
    val signOut: () -> Unit,
    val deleteCloudAccount: () -> Unit,
    val goNow: () -> Unit,
    val goBack: () -> Unit,
    val startNewThread: () -> Unit,
    val resolveCurrentThread: (SwitchCurrentChoice) -> Unit,
    val dismissCurrentSwitch: () -> Unit,
    val leaveNewStoppingPoint: () -> Unit,
    val setInput: (String) -> Unit,
    val saveText: () -> Unit,
    val voice: () -> Unit,
    val setAction: (String) -> Unit,
    val confirmStart: () -> Unit,
    val finishStarted: () -> Unit,
    val markCurrentComplete: () -> Unit,
    val archiveCurrent: () -> Unit,
    val showAllThreads: () -> Unit,
    val showRecentlyDeleted: () -> Unit,
    val showSettings: () -> Unit,
    val showDataPrivacy: () -> Unit,
    val setSearchQuery: (String) -> Unit,
    val openThread: (String) -> Unit,
    val returnToSelectedThread: () -> Unit,
    val editSelectedThread: () -> Unit,
    val completeSelectedThread: () -> Unit,
    val archiveSelectedThread: () -> Unit,
    val deleteSelectedThread: () -> Unit,
    val restoreThread: (String) -> Unit,
    val permanentlyDeleteThread: (String) -> Unit,
    val exportSelectedThread: () -> Unit,
    val deleteAllLocalThreads: () -> Unit,
    val requestWidgetPin: () -> Unit,
    val openMicrophoneSettings: () -> Unit,
    val openPrivacyPolicy: () -> Unit,
    val openTerms: () -> Unit,
    val openSupport: () -> Unit,
    val restorePurchases: () -> Unit = {},
)
